name: URL Availability Checker

# 触发工作流程的事件，这里设置为手动触发和推送到main分支
on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Check-CF-Proxy-IP-Global:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "httpx[http2]" openpyxl argparse pandas qqwry-py3

    - name: Install curl and unzip
      run: sudo apt-get install -y curl unzip

    - name: Prepare  directory
      run: |
        mkdir -p log
        mkdir -p zip-baipiao-eu-org

    - name: Download IPDB
      run: curl -L https://raw.githubusercontent.com/FW27623/qqwry/main/qqwry.dat -o qqwry.dat

    - name: Download from ipdb.api.030101.xyz
      run: curl http://ipdb.api.030101.xyz/?type=proxy > ipdbapi030101.txt

    - name: Download from zip.baipiao.eu.org
      run: curl -L https://zip.baipiao.eu.org/ -o zip-baipiao-eu-org.zip

    - name: Unzip zip-baipiao-eu-org.zip
      run: |
        unzip zip-baipiao-eu-org.zip -d ./zip-baipiao-eu-org
        # 打印当前工作目录下的所有文件和目录的绝对路径
        echo "当前工作目录的所有文件和目录的绝对路径:"
        find "$(pwd)" -type f
        # 打印新解压出的文件夹中的所有内容的绝对路径
        echo "新解压出的文件夹zip-baipiao-eu-org中的所有内容的绝对路径:"
        find "$(pwd)/zip-baipiao-eu-org" -type f


    - name: Run URL Availability Checker with ipdb.api.030101.xyz
      run: |
        python URL_Availability_Checker.py --input ipdbapi030101.txt --output ipdbapi030101-80.xlsx --port 80 --schema http  > log/ipdbapi030101-80.log
        python URL_Availability_Checker.py --input ipdbapi030101.txt --output ipdbapi030101-443.xlsx --port 443  --schema https > log/ipdbapi030101-443.log


    - name: Upload Results_ipdb-api-030101-xyz
      uses: actions/upload-artifact@v2
      with:
        name: ipdb-api-030101-xyz_results
        path: |
          ipdbapi030101-80.xlsx
          ipdbapi030101-443.xlsx

    - name: Run AutoSH_zip-baipiao-eu-org.sh
      run: |
        bash AutoSH_zip-baipiao-eu-org.sh > log/zip-baipiao-eu-org.log

    - name: Upload zip-baipiao-eu-org
      uses: actions/upload-artifact@v2
      with:
        name: zip-baipiao-eu-org_txt
        path: |
          zip-baipiao-eu-org/*
          cp zip-baipiao-eu-org/*.xlsx .

    - name: Run XLSX Combiner
      run: |
        # 打印当前工作目录下的所有文件和目录的绝对路径
        echo "当前工作目录的所有文件和目录的绝对路径:"
        find "$(pwd)" -type f
        # 打印新解压出的文件夹中的所有内容的绝对路径
        echo "新解压出的文件夹zip-baipiao-eu-org中的所有内容的绝对路径:"
        find "$(pwd)/zip-baipiao-eu-org" -type f
        
        python XLSX_Combiner.py

    - name: Upload CF-Proxy-IP-Global-Merged-xlsx
      uses: actions/upload-artifact@v2
      with:
        name: CF-Proxy-IP-Global-Merged-xlsx
        path: |
          CF-Proxy-IP-Global-Merged.xlsx

    - name: IPINFO PLUS CF-Proxy-IP-Global-Merged-xlsx with QQwry
      run: |
        python IP-INFO_Local_XLSX.py --input CF-Proxy-IP-Global-Merged.xlsx --output CF-Proxy-IP-Global-QQwry.xlsx --dat qqwry.dat

    - name: Upload CF-Proxy-IP-Global-QQwry-xlsx
      uses: actions/upload-artifact@v2
      with:
        name: CF-Proxy-IP-Global-QQwry-xlsx
        path: |
          CF-Proxy-IP-Global-QQwry.xlsx

    - name: Upload log
      uses: actions/upload-artifact@v2
      with:
        name: AANS_log
        path: |
          log/*

    - name: Upload All Pak
      uses: actions/upload-artifact@v2
      with:
        name: All Pak
        path: |
          /home/runner/work/Anti-Abuse_NetworkSecurity_System/Anti-Abuse_NetworkSecurity_System/*.xlsx
          /home/runner/work/Anti-Abuse_NetworkSecurity_System/Anti-Abuse_NetworkSecurity_System/**/*.xlsx
          /home/runner/work/Anti-Abuse_NetworkSecurity_System/Anti-Abuse_NetworkSecurity_System/*.txt
          /home/runner/work/Anti-Abuse_NetworkSecurity_System/Anti-Abuse_NetworkSecurity_System/**/*.txt
          /home/runner/work/Anti-Abuse_NetworkSecurity_System/Anti-Abuse_NetworkSecurity_System/*.log
          /home/runner/work/Anti-Abuse_NetworkSecurity_System/Anti-Abuse_NetworkSecurity_System/**/*.log
